from swift_tools.swift_types import *

@wrapper
class Accelerometer:

    def __init__(self): ...
    
    def enable(self): ...
    
    def disable(self): ...
    
    def get_acceleration(self) -> object: ...
