from swift_tools.swift_types import *

@wrapper
class Compass:

    def __init__(self): ...

    def enable(self): ...
    
    def disable(self): ...
    
    def get_orientation(self) -> object:...
    
    def get_field_uncalib(self) -> object: ...
